import { defaultSchema } from "rehype-sanitize";

/**
 * Structural subset of the `hast-util-sanitize` Schema type. We define it
 * inline so we don't take an extra direct dependency on `hast-util-sanitize`
 * just for a type import — it's already a transitive dep of rehype-sanitize.
 */
type Schema = {
  tagNames?: string[];
  attributes?: Record<string, Array<string | [string, ...Array<string | number | boolean>]>>;
  protocols?: Record<string, string[]>;
  strip?: string[];
  clobber?: string[];
  clobberPrefix?: string;
  ancestors?: Record<string, string[]>;
  required?: Record<string, Record<string, string | number | boolean>>;
  allowComments?: boolean;
  allowDoctypes?: boolean;
};

/**
 * A GitHub-parity sanitize schema.
 *
 * `rehype-sanitize` ships with a safe-by-default whitelist but it's too
 * restrictive for real READMEs — profile badges rely on `<picture>` /
 * `<source>` and contribution graphs ship as inline `<svg>`. We extend the
 * default schema rather than replace it so we keep all the XSS hardening.
 */
const base = defaultSchema as Schema;

export const githubSanitizeSchema: Schema = {
  ...base,
  tagNames: [
    ...(base.tagNames ?? []),
    // Responsive media
    "picture",
    "source",
    // Inline SVG (profile snakes, contribution graphs, typing animations)
    "svg",
    "path",
    "g",
    "defs",
    "linearGradient",
    "radialGradient",
    "stop",
    "circle",
    "rect",
    "line",
    "polyline",
    "polygon",
    "ellipse",
    "text",
    "tspan",
    "title",
    "desc",
    "use",
    "symbol",
    "clipPath",
    "mask",
    "pattern",
    "filter",
    "feGaussianBlur",
    "feOffset",
    "feMerge",
    "feMergeNode",
    "feColorMatrix",
    "feFlood",
    "feComposite",
    "animate",
    "animateTransform",
    "animateMotion",
    // Prose fixtures
    "br",
    "hr",
    "details",
    "summary",
    "sub",
    "sup",
    "kbd",
    "mark",
    "ins",
    "del",
    "abbr",
    "dfn",
    "cite",
    "q",
    "s",
    "u",
    "var",
    "samp",
    "small",
    "figure",
    "figcaption",
    "video",
    "audio",
    "track",
  ],
  attributes: {
    ...(base.attributes ?? {}),
    // Global attributes allowed on every tag
    "*": [
      ...((base.attributes?.["*"] as string[] | undefined) ?? []),
      "className",
      "style",
      "align",
      "id",
      "role",
      "aria-label",
      "aria-hidden",
      "aria-describedby",
      "aria-labelledby",
      "data-*",
    ],
    div: [["align", "left", "center", "right"]],
    p: [["align", "left", "center", "right"]],
    h1: [["align", "left", "center", "right"], "id"],
    h2: [["align", "left", "center", "right"], "id"],
    h3: [["align", "left", "center", "right"], "id"],
    h4: [["align", "left", "center", "right"], "id"],
    h5: [["align", "left", "center", "right"], "id"],
    h6: [["align", "left", "center", "right"], "id"],
    img: [
      "src",
      "alt",
      "width",
      "height",
      "loading",
      "decoding",
      "align",
      "srcset",
      "sizes",
      "title",
      "style",
    ],
    picture: ["className", "style"],
    source: ["src", "srcset", "media", "type", "sizes", "width", "height"],
    video: [
      "src",
      "controls",
      "autoplay",
      "loop",
      "muted",
      "playsinline",
      "poster",
      "width",
      "height",
      "preload",
    ],
    audio: ["src", "controls", "autoplay", "loop", "muted", "preload"],
    a: ["href", "title", "name", "target", "rel", "download"],
    input: ["type", "checked", "disabled", "readOnly"],
    // SVG attributes – expansive enough for contribution graphs / badges
    svg: [
      "xmlns",
      "xmlnsXlink",
      "viewBox",
      "width",
      "height",
      "fill",
      "stroke",
      "stroke-width",
      "preserveAspectRatio",
      "class",
      "style",
      "role",
      "aria-label",
    ],
    path: [
      "d",
      "fill",
      "fill-rule",
      "clip-rule",
      "stroke",
      "stroke-width",
      "stroke-linecap",
      "stroke-linejoin",
      "stroke-dasharray",
      "stroke-dashoffset",
      "transform",
      "opacity",
      "class",
      "style",
    ],
    g: ["fill", "stroke", "transform", "opacity", "class", "style"],
    rect: [
      "x",
      "y",
      "width",
      "height",
      "rx",
      "ry",
      "fill",
      "stroke",
      "stroke-width",
      "class",
      "style",
    ],
    circle: [
      "cx",
      "cy",
      "r",
      "fill",
      "stroke",
      "stroke-width",
      "class",
      "style",
    ],
    line: [
      "x1",
      "y1",
      "x2",
      "y2",
      "stroke",
      "stroke-width",
      "class",
      "style",
    ],
    polyline: ["points", "fill", "stroke", "stroke-width", "class", "style"],
    polygon: ["points", "fill", "stroke", "stroke-width", "class", "style"],
    ellipse: [
      "cx",
      "cy",
      "rx",
      "ry",
      "fill",
      "stroke",
      "stroke-width",
      "class",
      "style",
    ],
    text: [
      "x",
      "y",
      "dx",
      "dy",
      "fill",
      "stroke",
      "font-family",
      "font-size",
      "font-weight",
      "text-anchor",
      "class",
      "style",
    ],
    tspan: ["x", "y", "dx", "dy", "fill", "class", "style"],
    linearGradient: ["id", "x1", "x2", "y1", "y2", "gradientUnits"],
    radialGradient: ["id", "cx", "cy", "r", "fx", "fy", "gradientUnits"],
    stop: ["offset", "stop-color", "stop-opacity"],
    defs: [],
    use: ["href", "xlinkHref", "x", "y", "width", "height"],
    symbol: ["id", "viewBox"],
    clipPath: ["id"],
    mask: ["id", "x", "y", "width", "height"],
    pattern: ["id", "x", "y", "width", "height", "patternUnits", "viewBox"],
    filter: ["id", "x", "y", "width", "height"],
    feGaussianBlur: ["in", "stdDeviation", "result"],
    feOffset: ["in", "dx", "dy", "result"],
    feMerge: [],
    feMergeNode: ["in"],
    feColorMatrix: ["in", "type", "values", "result"],
    feFlood: ["flood-color", "flood-opacity", "result"],
    feComposite: ["in", "in2", "operator", "result"],
    animate: [
      "attributeName",
      "from",
      "to",
      "dur",
      "begin",
      "end",
      "repeatCount",
      "values",
    ],
    animateTransform: [
      "attributeName",
      "type",
      "from",
      "to",
      "dur",
      "begin",
      "end",
      "repeatCount",
      "values",
    ],
    table: [["align", "left", "center", "right"]],
    th: [["align", "left", "center", "right"], "colSpan", "rowSpan"],
    td: [["align", "left", "center", "right"], "colSpan", "rowSpan"],
    details: ["open"],
    summary: [],
    kbd: [],
  },
  protocols: {
    ...(base.protocols ?? {}),
    href: ["http", "https", "mailto", "tel", "#"],
    src: ["http", "https", "data"],
    cite: ["http", "https"],
  },
  // Strip javascript: URLs. `defaultSchema` already does this, but we add an
  // explicit clobberPrefix for DOM-clobbering defense in depth.
  clobberPrefix: "markdown-studio-",
  clobber: ["name", "id"],
};
